# Data cleaning for anomalies: to long , to short

In [1]:
import pandas as pd
import pyodbc  
import matplotlib.pyplot as plt

## Connection with db

In [2]:
conn = pyodbc.connect(r'DRIVER={ODBC Driver 17 for SQL Server};SERVER=;DATABASE=CRH;Trusted_Connection=yes;')
cursor = conn.cursor()

## Data in dataframe

In [3]:
query =  """
        SELECT c.ID, c.InstanceId, TestStartTime, TestFinishTime, Gender, Qualification
        FROM CandidateResultFCA cf 
        JOIN Candidate c
        ON cf.CandidateID = c.ID and cf.InstanceID = c.InstanceID
        """
df = pd.read_sql_query(query, conn)

C:\Users\Lorem\AppData\Local\Temp\ipykernel_17836\970591828.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

In [ ]:
fca_csv = "..\\files\\csv\\fca_investigate.csv" # TODO: outdated 
fca_df = pd.read_csv(fca_csv)

In [5]:
fca_df

,InstrumentClassId,CandidateId,InstanceId,ItemId,Answer1,Answer2,Answer3,CorrectAnswers,TimeSpent
0,1137,3164626,1,407,3,4,5,"2, 3, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0",116
1,1137,3164626,1,410,0,0,0,"2, 5, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0",191
2,1137,3164626,1,411,4,1,5,"5, 4, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0",121
3,1137,3164626,1,412,3,5,4,"1, 2, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0",45
4,1137,3164626,1,413,5,3,1,"1, 5, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0",75
5,1137,3164626,1,414,4,3,5,"1, 5, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0",75
6,1137,3164626,1,415,5,4,3,"5, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0",112
7,1137,3164626,1,416,5,3,4,"3, 1, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0",68
8,1137,3164626,1,417,5,3,4,"4, 5, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0",66
9,1137,3164626,1,418,5,3,4,"4, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0",1268
10,1137,3164626,1,419,4,3,5,"3, 5, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0",69
11,1137,3164626,1,420,5,3,4,"3, 4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0",71
12,1137,3164626,1,421,3,4,5,"2, 3, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0",35
13,1137,3164626,1,422,5,4,3,"5, 2, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0",81
14,1119,4041888,1,407,2,3,4,"1, 5, 3, 3, 2, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...",117
15,1119,4041888,1,408,3,4,2,"3, 5, 2, 1, 3, 5, 2, 4, 5, 0, 0, 0, 0, 0, 0, 0...",144
16,1119,4041888,1,409,4,2,3,"5, 2, 3, 4, 1, 3, 2, 3, 4, 0, 0, 0, 0, 0, 0, 0...",127
17,1119,4041888,1,410,3,4,1,"1, 4, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0",109
18,1119,4041888,1,411,3,2,4,"5, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0",88
19,1119,4041888,1,412,3,1,5,"1, 3, 4, 3, 4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...",91
20,1119,4041888,1,413,4,3,2,"1, 4, 2, 4, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...",92
21,1119,4041888,1,414,3,4,1,"4, 3, 2, 2, 5, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...",184
22,1119,4041888,1,415,2,3,4,"4, 2, 3, 2, 4, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...",296
23,1119,4041888,1,416,2,5,3,"3, 1, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0",319
24,1119,4041888,1,417,1,4,3,"2, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0",160
25,1119,4041888,1,418,5,1,3,"5, 3, 2, 2, 3, 5, 1, 4, 2, 0, 0, 0, 0, 0, 0, 0...",162
26,1119,4041888,1,419,5,4,2,"2, 4, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0",100
27,1119,4041888,1,420,4,2,3,"2, 4, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0",293
28,1119,4041888,1,421,4,2,3,"1, 4, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0",227
29,1119,4041888,1,422,4,3,2,"1, 5, 4, 3, 4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...",155
30,1119,4041888,1,423,5,2,1,"3, 2, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0",233
31,1119,4041888,1,424,2,3,4,"3, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0",146
32,1119,4041888,1,425,4,2,3,"3, 2, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0",557
33,1119,4041888,1,426,1,4,2,"5, 4, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0",86
34,106,4044109,1,220,5,4,2,"3, 4, 1, 5, 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...",39
35,106,4044109,1,221,4,3,5,"3, 4, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0",43
36,106,4044109,1,222,5,4,3,"3, 5, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0",97
37,106,4044109,1,223,4,5,3,"1, 4, 5, 3, 5, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...",106
38,106,4044109,1,224,2,5,3,"1, 4, 5, 3, 5, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...",145
39,106,4044109,1,225,4,1,5,"4, 2, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0",566
40,106,4044109,1,226,3,4,5,"5, 4, 2, 3, 5, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...",150
41,106,4044109,1,227,4,2,5,"4, 2, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0",35
42,106,4044109,1,228,5,3,4,"1, 5, 3, 4, 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...",165
43,106,4044109,1,229,1,5,4,"2, 5, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0",95
44,106,4044109,1,230,5,4,1,"2, 3, 5, 2, 1, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...",92
45,106,4044109,1,231,3,5,4,"5, 2, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0",21
46,106,4044109,1,232,3,4,5,"3, 4, 5, 3, 4, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...",64
47,106,4044109,1,233,3,5,2,"4, 5, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0",66
48,106,4044109,1,234,5,3,2,"5, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0",85
49,106,4044109,1,235,2,5,3,"4, 1, 5, 5, 1, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...",156
50,106,4044109,1,236,5,4,2,"5, 4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0",36
51,106,4044109,1,237,4,2,5,"5, 4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0",28
52,106,4044109,1,238,2,1,5,"3, 2, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0",41
53,106,4044109,1,239,1,2,5,"1, 3, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0",417
54,106,4044109,1,240,2,3,5,"5, 1, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0",223
55,106,4044109,1,241,5,3,2,"3, 1, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0",99

In [6]:
df

,ID,TestStartTime,TestFinishTime,Gender,Qualification
0,992,2023-09-08 07:07:29.533,2023-09-08 07:09:26.197,Gender_Male,Qualification_Unknown
1,1124,2023-09-27 16:03:59.047,2023-09-27 16:46:19.430,Gender_Female,Qualification_Unknown
2,1158,2023-09-29 14:43:52.897,2023-09-29 15:04:57.667,Gender_Male,Qualification_Bachelor
3,1285,2023-10-13 09:23:15.460,2023-10-13 09:52:39.973,Gender_Male,Qualification_Unknown
4,1485,2023-10-23 07:47:29.690,2023-10-23 08:19:23.397,Gender_Male,Qualification_Bachelor
...,...,...,...,...,...
160213,4982046,2024-02-19 08:34:39.187,2024-02-19 09:04:19.400,Gender_Male,Qualification_Unknown
160214,4982097,2024-02-08 10:58:04.770,2024-02-08 11:35:20.650,Gender_Male,Qualification_Unknown
160215,4982163,2024-02-22 12:34:33.257,2024-02-22 13:26:31.967,Gender_Male,Qualification_Unknown
160216,4982214,2024-02-01 12:47:48.603,2024-02-01 13:20:29.923,Gender_Male,Qualification_Unknown
160217,4982278,2024-01-30 20:59:19.773,2024-01-30 21:23:00.083,Gender_Female,Qualification_Secondary

In [6]:
fca_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   InstrumentClassId  56 non-null     int64
 1   CandidateId        56 non-null     int64
 2   InstanceId         56 non-null     int64
 3   ItemId             56 non-null     int64
 4   Answer1            56 non-null     int64
 5   Answer2            56 non-null     int64
 6   Answer3            56 non-null     int64
 7   CorrectAnswers     56 non-null     object
 8   TimeSpent          56 non-null     int64
dtypes: int64(8), object(1)
memory usage: 4.1+ KB

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160218 entries, 0 to 160217
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID              160218 non-null  int64
 1   TestStartTime   160218 non-null  datetime64[ns]
 2   TestFinishTime  160218 non-null  datetime64[ns]
 3   Gender          160218 non-null  object
 4   Qualification   160218 non-null  object
dtypes: datetime64[ns](2), int64(1), object(2)
memory usage: 6.1+ MB

In [8]:
df['Gender'].value_counts()

Gender
Gender_Female     75593
Gender_Male       73978
Gender_Unknown    10647
Name: count, dtype: int64

## Data cleaning

In [9]:
df['Gender'] = df['Gender'].replace({
    'Gender_Female': 'female',
    'Gender_Male': 'male',
    'Gender_Unknown': 'other'
})

In [10]:
df['Qualification'].value_counts()

Qualification
Qualification_Unknown         125401
Qualification_Bachelor         13059
Qualification_Master           12775
Qualification_Secondary         5864
Qualification_PostGraduate      1267
Qualification_Professional       909
Qualification_MBA                488
Qualification_Vocational         370
Qualification_PHD                 84
                                   1
Name: count, dtype: int64

In [11]:
df['Qualification'] = df['Qualification'].replace({
    'Qualification_Unknown': 'unknown',
    'Qualification_Bachelor': 'bachelor',
    'Qualification_Master': 'master',
    'Qualification_Secondary': 'secondary',
    'Qualification_PostGraduate': 'postgraduate',
    'Qualification_Professional': 'professional',
    'Qualification_MBA': 'mba',
    'Qualification_Vocational': 'vocational',
    'Qualification_PHD': 'phd'
})
df

,ID,TestStartTime,TestFinishTime,Gender,Qualification
0,992,2023-09-08 07:07:29.533,2023-09-08 07:09:26.197,male,unknown
1,1124,2023-09-27 16:03:59.047,2023-09-27 16:46:19.430,female,unknown
2,1158,2023-09-29 14:43:52.897,2023-09-29 15:04:57.667,male,bachelor
3,1285,2023-10-13 09:23:15.460,2023-10-13 09:52:39.973,male,unknown
4,1485,2023-10-23 07:47:29.690,2023-10-23 08:19:23.397,male,bachelor
...,...,...,...,...,...
160213,4982046,2024-02-19 08:34:39.187,2024-02-19 09:04:19.400,male,unknown
160214,4982097,2024-02-08 10:58:04.770,2024-02-08 11:35:20.650,male,unknown
160215,4982163,2024-02-22 12:34:33.257,2024-02-22 13:26:31.967,male,unknown
160216,4982214,2024-02-01 12:47:48.603,2024-02-01 13:20:29.923,male,unknown
160217,4982278,2024-01-30 20:59:19.773,2024-01-30 21:23:00.083,female,secondary

In [12]:
df = df[df['TestFinishTime'] - df['TestStartTime'] != pd.Timedelta(hours=1)]
df

,ID,TestStartTime,TestFinishTime,Gender,Qualification
0,992,2023-09-08 07:07:29.533,2023-09-08 07:09:26.197,male,unknown
1,1124,2023-09-27 16:03:59.047,2023-09-27 16:46:19.430,female,unknown
2,1158,2023-09-29 14:43:52.897,2023-09-29 15:04:57.667,male,bachelor
3,1285,2023-10-13 09:23:15.460,2023-10-13 09:52:39.973,male,unknown
4,1485,2023-10-23 07:47:29.690,2023-10-23 08:19:23.397,male,bachelor
...,...,...,...,...,...
160213,4982046,2024-02-19 08:34:39.187,2024-02-19 09:04:19.400,male,unknown
160214,4982097,2024-02-08 10:58:04.770,2024-02-08 11:35:20.650,male,unknown
160215,4982163,2024-02-22 12:34:33.257,2024-02-22 13:26:31.967,male,unknown
160216,4982214,2024-02-01 12:47:48.603,2024-02-01 13:20:29.923,male,unknown
160217,4982278,2024-01-30 20:59:19.773,2024-01-30 21:23:00.083,female,secondary

In [13]:
remaining_rows = df[(df['TestFinishTime'] - df['TestStartTime'] == pd.Timedelta(hours=1))]
if remaining_rows.empty:
    print("Er zijn geen rijen meer met een tijdsverschil van precies 1 uur.")
else:
    print("Er zijn nog steeds rijen met een tijdsverschil van precies 1 uur.")

Er zijn geen rijen meer met een tijdsverschil van precies 1 uur.

### Kolom toevoegen met hoelang ze er over gedaan hebben

In [14]:
df['test_duration'] = df['TestFinishTime'] - df['TestStartTime']
df['test_duration_seconds'] = df['test_duration'].dt.total_seconds()
df['test_duration_minutes'] = df['test_duration'].dt.total_seconds() / 60

C:\Users\Lorem\AppData\Local\Temp\ipykernel_18628\2198987834.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['test_duration'] = df['TestFinishTime'] - df['TestStartTime']
C:\Users\Lorem\AppData\Local\Temp\ipykernel_18628\2198987834.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['test_duration_seconds'] = df['test_duration'].dt.total_seconds()
C:\Users\Lorem\AppData\Local\Temp\ipykernel_18628\2198987834.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['test_duration_minutes'] = df['test_duration'].dt.total_seconds() / 60

In [15]:
df = df.drop(columns=['test_duration', 'TestStartTime', 'TestFinishTime'])
df

,ID,Gender,Qualification,test_duration_seconds,test_duration_minutes
0,992,male,unknown,116.664,1.944400
1,1124,female,unknown,2540.383,42.339717
2,1158,male,bachelor,1264.770,21.079500
3,1285,male,unknown,1764.513,29.408550
4,1485,male,bachelor,1913.707,31.895117
...,...,...,...,...,...
160213,4982046,male,unknown,1780.213,29.670217
160214,4982097,male,unknown,2235.880,37.264667
160215,4982163,male,unknown,3118.710,51.978500
160216,4982214,male,unknown,1961.320,32.688667
160217,4982278,female,secondary,1420.310,23.671833

In [ ]:
fca_time = df.join(fca_df, [''])