# Preprocessing

In [1]:
import pyodbc
import pandas as pd

In [2]:
df_test = pd.read_csv('../../../decoded_data/SJT/FactTest.csv')
df_question = pd.read_csv('../../../decoded_data/SJT/FactQuestionSJT.csv')

In [3]:
df_test.drop(columns=['VersionNumber', 'TimeSpent', 'Test'], inplace=True)
df_test.head()

   CandidateKey  CreatedDateKey  TestKey
0      49373671        20231108   160068
1      49546791        20231207   160069
2      35275031        20171221   160070
3      37190041        20181009   160071
4      47543331        20230119   160072

In [4]:
df_question.drop(columns=['InstanceID', 'Test'], inplace=True)
df_question.head()

,QuestionKey,ItemID,AnswerSequence1,AnswerSequence2,AnswerSequence3,TimeSpent,TestKey
0,1,1,5,4,2,181,160068
1,2,2,4,3,2,172,160068
2,3,3,4,2,3,136,160068
3,4,4,3,2,4,266,160068
4,5,5,2,5,1,198,160068

In [5]:
df = df_question.merge(df_test, on='TestKey')
df.head()

,QuestionKey,ItemID,AnswerSequence1,AnswerSequence2,AnswerSequence3,TimeSpent,TestKey,CandidateKey,CreatedDateKey
0,1,1,5,4,2,181,160068,49373671,20231108
1,2,2,4,3,2,172,160068,49373671,20231108
2,3,3,4,2,3,136,160068,49373671,20231108
3,4,4,3,2,4,266,160068,49373671,20231108
4,5,5,2,5,1,198,160068,49373671,20231108

### CreatedDate

In [6]:
df["CreatedDateKey"] = pd.to_datetime(df.CreatedDateKey, format="%Y%m%d")
df.head()

,QuestionKey,ItemID,AnswerSequence1,AnswerSequence2,AnswerSequence3,TimeSpent,TestKey,CandidateKey,CreatedDateKey
0,1,1,5,4,2,181,160068,49373671,2023-11-08
1,2,2,4,3,2,172,160068,49373671,2023-11-08
2,3,3,4,2,3,136,160068,49373671,2023-11-08
3,4,4,3,2,4,266,160068,49373671,2023-11-08
4,5,5,2,5,1,198,160068,49373671,2023-11-08

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89622 entries, 0 to 89621
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   QuestionKey      89622 non-null  int64
 1   ItemID           89622 non-null  int64
 2   AnswerSequence1  89622 non-null  int64
 3   AnswerSequence2  89622 non-null  int64
 4   AnswerSequence3  89622 non-null  int64
 5   TimeSpent        89622 non-null  int64
 6   TestKey          89622 non-null  int64
 7   CandidateKey     89622 non-null  int64
 8   CreatedDateKey   89622 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(8)
memory usage: 6.2 MB

In [8]:
df['Year'] = pd.DatetimeIndex(df['CreatedDateKey']).year
df['Month'] = pd.DatetimeIndex(df['CreatedDateKey']).month
df['Day'] = pd.DatetimeIndex(df['CreatedDateKey']).dayofweek
df.drop(columns=['CreatedDateKey'], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89622 entries, 0 to 89621
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   QuestionKey      89622 non-null  int64
 1   ItemID           89622 non-null  int64
 2   AnswerSequence1  89622 non-null  int64
 3   AnswerSequence2  89622 non-null  int64
 4   AnswerSequence3  89622 non-null  int64
 5   TimeSpent        89622 non-null  int64
 6   TestKey          89622 non-null  int64
 7   CandidateKey     89622 non-null  int64
 8   Year             89622 non-null  int32
 9   Month            89622 non-null  int32
 10  Day              89622 non-null  int32
dtypes: int32(3), int64(8)
memory usage: 6.5 MB

In [9]:
df.head()

,QuestionKey,ItemID,AnswerSequence1,AnswerSequence2,AnswerSequence3,TimeSpent,TestKey,CandidateKey,Year,Month,Day
0,1,1,5,4,2,181,160068,49373671,2023,11,2
1,2,2,4,3,2,172,160068,49373671,2023,11,2
2,3,3,4,2,3,136,160068,49373671,2023,11,2
3,4,4,3,2,4,266,160068,49373671,2023,11,2
4,5,5,2,5,1,198,160068,49373671,2023,11,2

### Candidate information

## Cleaning

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89622 entries, 0 to 89621
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   QuestionKey      89622 non-null  int64
 1   ItemID           89622 non-null  int64
 2   AnswerSequence1  89622 non-null  int64
 3   AnswerSequence2  89622 non-null  int64
 4   AnswerSequence3  89622 non-null  int64
 5   TimeSpent        89622 non-null  int64
 6   TestKey          89622 non-null  int64
 7   CandidateKey     89622 non-null  int64
 8   Year             89622 non-null  int32
 9   Month            89622 non-null  int32
 10  Day              89622 non-null  int32
dtypes: int32(3), int64(8)
memory usage: 6.5 MB

#### TimeSpent

In [11]:
time_zero = (df.TimeSpent == 0).sum()
time_not_zero = (df.TimeSpent != 0).sum()

print("Amount of test where time spent is zero:", time_zero)
print("Amount of test where time spent is not zero:", time_not_zero)

Amount of test where time spent is zero: 55942
Amount of test where time spent is not zero: 33680

As there are more test where the time spent is registered as zero (not a real possibility), we create two datasets. One only containing the instances where the timespent is a valid number and the other not containing the "TimeSpent' column at all. Depend on the model you want to train, a different dataset will apply.

In [12]:
df_no_time = df.drop(columns=['TimeSpent'])
df_time = df[df.TimeSpent != 0]

In [13]:
df_no_time.head()

,QuestionKey,ItemID,AnswerSequence1,AnswerSequence2,AnswerSequence3,TestKey,CandidateKey,Year,Month,Day
0,1,1,5,4,2,160068,49373671,2023,11,2
1,2,2,4,3,2,160068,49373671,2023,11,2
2,3,3,4,2,3,160068,49373671,2023,11,2
3,4,4,3,2,4,160068,49373671,2023,11,2
4,5,5,2,5,1,160068,49373671,2023,11,2

In [14]:
df_time.head()

,QuestionKey,ItemID,AnswerSequence1,AnswerSequence2,AnswerSequence3,TimeSpent,TestKey,CandidateKey,Year,Month,Day
0,1,1,5,4,2,181,160068,49373671,2023,11,2
1,2,2,4,3,2,172,160068,49373671,2023,11,2
2,3,3,4,2,3,136,160068,49373671,2023,11,2
3,4,4,3,2,4,266,160068,49373671,2023,11,2
4,5,5,2,5,1,198,160068,49373671,2023,11,2

In [15]:
df = df_no_time

In [16]:
df_melted = df.melt(id_vars=['TestKey', 'ItemID'], 
                    value_vars=['AnswerSequence1', 
                                'AnswerSequence2',
                                'AnswerSequence3'], 
                    var_name='answer_type', 
                    value_name='Answer')
df_melted['QuestionNr'] = df_melted['answer_type'].str.slice(len('AnswerSequence')).astype('Int8')
df_melted.drop(columns=["answer_type"], inplace=True)

In [17]:
df_melted

        TestKey  ItemID  Answer  QuestionNr
0        160068       1       5           1
1        160068       2       4           1
2        160068       3       4           1
3        160068       4       3           1
4        160068       5       2           1
...         ...     ...     ...         ...
268861   166961       0       0           3
268862   166961       0       0           3
268863   166961       0       0           3
268864   166961       0       0           3
268865   166961       0       0           3

[268866 rows x 4 columns]

In [18]:
df_pivot = df_melted.pivot_table(index='TestKey', 
                                columns=['ItemID', 'QuestionNr'], 
                                values='Answer', 
                                aggfunc='first')
df_pivot.columns = [f'Q{q}_A{a}' for q, a in df_pivot.columns]
df_pivot.fillna(0.0, inplace=True)

In [19]:
df_pivot.head()

,Q0_A1,Q0_A2,Q0_A3,Q1_A1,Q1_A2,Q1_A3,Q2_A1,Q2_A2,Q2_A3,Q3_A1,...,Q10_A3,Q11_A1,Q11_A2,Q11_A3,Q12_A1,Q12_A2,Q12_A3,Q13_A1,Q13_A2,Q13_A3
TestKey,,,,,,,,,,,,,,,,,,,,,
160068,0.0,0.0,0.0,5.0,4.0,2.0,4.0,3.0,2.0,4.0,...,3.0,4.0,3.0,5.0,3.0,5.0,4.0,4.0,3.0,2.0
160069,0.0,0.0,0.0,2.0,4.0,5.0,4.0,3.0,5.0,5.0,...,2.0,4.0,2.0,5.0,4.0,5.0,2.0,3.0,4.0,2.0
160070,0.0,0.0,0.0,3.0,5.0,1.0,1.0,3.0,4.0,1.0,...,5.0,1.0,2.0,5.0,4.0,3.0,2.0,4.0,1.0,5.0
160071,0.0,0.0,0.0,2.0,4.0,3.0,4.0,5.0,2.0,3.0,...,3.0,2.0,5.0,4.0,3.0,4.0,5.0,5.0,2.0,4.0
160072,0.0,0.0,0.0,4.0,2.0,3.0,4.0,1.0,2.0,2.0,...,5.0,2.0,1.0,4.0,4.0,2.0,3.0,2.0,3.0,5.0

In [20]:
df_pivot.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6894 entries, 160068 to 166961
Data columns (total 42 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Q0_A1   6894 non-null   float64
 1   Q0_A2   6894 non-null   float64
 2   Q0_A3   6894 non-null   float64
 3   Q1_A1   6894 non-null   float64
 4   Q1_A2   6894 non-null   float64
 5   Q1_A3   6894 non-null   float64
 6   Q2_A1   6894 non-null   float64
 7   Q2_A2   6894 non-null   float64
 8   Q2_A3   6894 non-null   float64
 9   Q3_A1   6894 non-null   float64
 10  Q3_A2   6894 non-null   float64
 11  Q3_A3   6894 non-null   float64
 12  Q4_A1   6894 non-null   float64
 13  Q4_A2   6894 non-null   float64
 14  Q4_A3   6894 non-null   float64
 15  Q5_A1   6894 non-null   float64
 16  Q5_A2   6894 non-null   float64
 17  Q5_A3   6894 non-null   float64
 18  Q6_A1   6894 non-null   float64
 19  Q6_A2   6894 non-null   float64
 20  Q6_A3   6894 non-null   float64
 21  Q7_A1   6894 non-null   float64
 22  Q7_A2   6894 non-null   float64
 23  Q7_A3   6894 non-null   float64
 24  Q8_A1   6894 non-null   float64
 25  Q8_A2   6894 non-null   float64
 26  Q8_A3   6894 non-null   float64
 27  Q9_A1   6894 non-null   float64
 28  Q9_A2   6894 non-null   float64
 29  Q9_A3   6894 non-null   float64
 30  Q10_A1  6894 non-null   float64
 31  Q10_A2  6894 non-null   float64
 32  Q10_A3  6894 non-null   float64
 33  Q11_A1  6894 non-null   float64
 34  Q11_A2  6894 non-null   float64
 35  Q11_A3  6894 non-null   float64
 36  Q12_A1  6894 non-null   float64
 37  Q12_A2  6894 non-null   float64
 38  Q12_A3  6894 non-null   float64
 39  Q13_A1  6894 non-null   float64
 40  Q13_A2  6894 non-null   float64
 41  Q13_A3  6894 non-null   float64
dtypes: float64(42)
memory usage: 2.3 MB

In [21]:
df_add = df[["TestKey", "Year", "Month", "Day"]]
df_pivot = df_pivot.merge(df_add, on='TestKey')
df_pivot.head()

,TestKey,Q0_A1,Q0_A2,Q0_A3,Q1_A1,Q1_A2,Q1_A3,Q2_A1,Q2_A2,Q2_A3,...,Q11_A3,Q12_A1,Q12_A2,Q12_A3,Q13_A1,Q13_A2,Q13_A3,Year,Month,Day
0,160068,0.0,0.0,0.0,5.0,4.0,2.0,4.0,3.0,2.0,...,5.0,3.0,5.0,4.0,4.0,3.0,2.0,2023,11,2
1,160068,0.0,0.0,0.0,5.0,4.0,2.0,4.0,3.0,2.0,...,5.0,3.0,5.0,4.0,4.0,3.0,2.0,2023,11,2
2,160068,0.0,0.0,0.0,5.0,4.0,2.0,4.0,3.0,2.0,...,5.0,3.0,5.0,4.0,4.0,3.0,2.0,2023,11,2
3,160068,0.0,0.0,0.0,5.0,4.0,2.0,4.0,3.0,2.0,...,5.0,3.0,5.0,4.0,4.0,3.0,2.0,2023,11,2
4,160068,0.0,0.0,0.0,5.0,4.0,2.0,4.0,3.0,2.0,...,5.0,3.0,5.0,4.0,4.0,3.0,2.0,2023,11,2

In [22]:
df_dupl = df_pivot.drop_duplicates()

In [23]:
df_pivot

,TestKey,Q0_A1,Q0_A2,Q0_A3,Q1_A1,Q1_A2,Q1_A3,Q2_A1,Q2_A2,Q2_A3,...,Q11_A3,Q12_A1,Q12_A2,Q12_A3,Q13_A1,Q13_A2,Q13_A3,Year,Month,Day
0,160068,0.0,0.0,0.0,5.0,4.0,2.0,4.0,3.0,2.0,...,5.0,3.0,5.0,4.0,4.0,3.0,2.0,2023,11,2
1,160068,0.0,0.0,0.0,5.0,4.0,2.0,4.0,3.0,2.0,...,5.0,3.0,5.0,4.0,4.0,3.0,2.0,2023,11,2
2,160068,0.0,0.0,0.0,5.0,4.0,2.0,4.0,3.0,2.0,...,5.0,3.0,5.0,4.0,4.0,3.0,2.0,2023,11,2
3,160068,0.0,0.0,0.0,5.0,4.0,2.0,4.0,3.0,2.0,...,5.0,3.0,5.0,4.0,4.0,3.0,2.0,2023,11,2
4,160068,0.0,0.0,0.0,5.0,4.0,2.0,4.0,3.0,2.0,...,5.0,3.0,5.0,4.0,4.0,3.0,2.0,2023,11,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89617,166961,0.0,0.0,0.0,1.0,2.0,3.0,1.0,2.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2024,9,0
89618,166961,0.0,0.0,0.0,1.0,2.0,3.0,1.0,2.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2024,9,0
89619,166961,0.0,0.0,0.0,1.0,2.0,3.0,1.0,2.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2024,9,0
89620,166961,0.0,0.0,0.0,1.0,2.0,3.0,1.0,2.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2024,9,0
89621,166961,0.0,0.0,0.0,1.0,2.0,3.0,1.0,2.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2024,9,0

In [24]:
df_dupl

,TestKey,Q0_A1,Q0_A2,Q0_A3,Q1_A1,Q1_A2,Q1_A3,Q2_A1,Q2_A2,Q2_A3,...,Q11_A3,Q12_A1,Q12_A2,Q12_A3,Q13_A1,Q13_A2,Q13_A3,Year,Month,Day
0,160068,0.0,0.0,0.0,5.0,4.0,2.0,4.0,3.0,2.0,...,5.0,3.0,5.0,4.0,4.0,3.0,2.0,2023,11,2
13,160069,0.0,0.0,0.0,2.0,4.0,5.0,4.0,3.0,5.0,...,5.0,4.0,5.0,2.0,3.0,4.0,2.0,2023,12,3
26,160070,0.0,0.0,0.0,3.0,5.0,1.0,1.0,3.0,4.0,...,5.0,4.0,3.0,2.0,4.0,1.0,5.0,2017,12,3
39,160071,0.0,0.0,0.0,2.0,4.0,3.0,4.0,5.0,2.0,...,4.0,3.0,4.0,5.0,5.0,2.0,4.0,2018,10,1
52,160072,0.0,0.0,0.0,4.0,2.0,3.0,4.0,1.0,2.0,...,4.0,4.0,2.0,3.0,2.0,3.0,5.0,2023,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89557,166957,0.0,0.0,0.0,3.0,4.0,1.0,5.0,3.0,4.0,...,4.0,5.0,4.0,3.0,5.0,4.0,3.0,2024,7,2
89570,166958,0.0,0.0,0.0,5.0,4.0,3.0,3.0,4.0,2.0,...,5.0,3.0,5.0,1.0,5.0,1.0,2.0,2024,7,2
89583,166959,0.0,0.0,0.0,5.0,1.0,3.0,2.0,3.0,5.0,...,5.0,2.0,5.0,4.0,5.0,4.0,3.0,2024,7,2
89596,166960,0.0,0.0,0.0,1.0,2.0,3.0,2.0,3.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022,5,2
89609,166961,0.0,0.0,0.0,1.0,2.0,3.0,1.0,2.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2024,9,0

In [25]:
df_dupl.set_index('TestKey', inplace=True)
df_dupl.to_csv('../csv/preprocessed_data.csv')