# Preprocessing

In [1]:
import pyodbc
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
df_test = pd.read_csv('../../../decoded_data/PAQ/FactTest.csv')
df_question = pd.read_csv('../../../decoded_data/PAQ/FactQuestionPAQ.csv')

In [3]:
df_test.drop(columns=['VersionNumber', 'Test'], inplace=True)
df_test.head()

   CandidateKey  CreatedDateKey  TestKey
0      38114181        20190123   166962
1      38046331        20190110   166963
2      38114191        20190128   166964
3      38201141        20190206   166965
4      38337341        20190227   166966

In [4]:
df_question.drop(columns=['InstanceID', 'Test'], inplace=True)
df_question.head()

   QuestionKey LeftStatement RightStatement  AnswerVal  TestKey
0            1         BEW_1          BEH_1          1   166962
1            2         REA_1          OPT_1          5   166962
2            3         REG_1          AFW_1          5   166962
3            4         RUS_1          ENE_1          5   166962
4            5         OVE_1          GED_1          5   166962

In [5]:
df = df_question.merge(df_test, on='TestKey')
df.head()

,QuestionKey,LeftStatement,RightStatement,AnswerVal,TestKey,CandidateKey,CreatedDateKey
0,1,BEW_1,BEH_1,1,166962,38114181,20190123
1,2,REA_1,OPT_1,5,166962,38114181,20190123
2,3,REG_1,AFW_1,5,166962,38114181,20190123
3,4,RUS_1,ENE_1,5,166962,38114181,20190123
4,5,OVE_1,GED_1,5,166962,38114181,20190123

### CreatedDate

In [6]:
df["CreatedDateKey"] = pd.to_datetime(df.CreatedDateKey, format="%Y%m%d")
df.head()

,QuestionKey,LeftStatement,RightStatement,AnswerVal,TestKey,CandidateKey,CreatedDateKey
0,1,BEW_1,BEH_1,1,166962,38114181,2019-01-23
1,2,REA_1,OPT_1,5,166962,38114181,2019-01-23
2,3,REG_1,AFW_1,5,166962,38114181,2019-01-23
3,4,RUS_1,ENE_1,5,166962,38114181,2019-01-23
4,5,OVE_1,GED_1,5,166962,38114181,2019-01-23

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2852280 entries, 0 to 2852279
Data columns (total 7 columns):
 #   Column          Dtype
---  ------          -----
 0   QuestionKey     int64
 1   LeftStatement   object
 2   RightStatement  object
 3   AnswerVal       int64
 4   TestKey         int64
 5   CandidateKey    int64
 6   CreatedDateKey  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(2)
memory usage: 152.3+ MB

In [8]:
df['Year'] = pd.DatetimeIndex(df['CreatedDateKey']).year
df['Month'] = pd.DatetimeIndex(df['CreatedDateKey']).month
df['Day'] = pd.DatetimeIndex(df['CreatedDateKey']).dayofweek
df.drop(columns=['CreatedDateKey'], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2852280 entries, 0 to 2852279
Data columns (total 9 columns):
 #   Column          Dtype
---  ------          -----
 0   QuestionKey     int64
 1   LeftStatement   object
 2   RightStatement  object
 3   AnswerVal       int64
 4   TestKey         int64
 5   CandidateKey    int64
 6   Year            int32
 7   Month           int32
 8   Day             int32
dtypes: int32(3), int64(4), object(2)
memory usage: 163.2+ MB

In [9]:
df.head()

,QuestionKey,LeftStatement,RightStatement,AnswerVal,TestKey,CandidateKey,Year,Month,Day
0,1,BEW_1,BEH_1,1,166962,38114181,2019,1,2
1,2,REA_1,OPT_1,5,166962,38114181,2019,1,2
2,3,REG_1,AFW_1,5,166962,38114181,2019,1,2
3,4,RUS_1,ENE_1,5,166962,38114181,2019,1,2
4,5,OVE_1,GED_1,5,166962,38114181,2019,1,2

## Cleaning

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2852280 entries, 0 to 2852279
Data columns (total 9 columns):
 #   Column          Dtype
---  ------          -----
 0   QuestionKey     int64
 1   LeftStatement   object
 2   RightStatement  object
 3   AnswerVal       int64
 4   TestKey         int64
 5   CandidateKey    int64
 6   Year            int32
 7   Month           int32
 8   Day             int32
dtypes: int32(3), int64(4), object(2)
memory usage: 163.2+ MB

In [11]:
df.dropna(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2852280 entries, 0 to 2852279
Data columns (total 9 columns):
 #   Column          Dtype
---  ------          -----
 0   QuestionKey     int64
 1   LeftStatement   object
 2   RightStatement  object
 3   AnswerVal       int64
 4   TestKey         int64
 5   CandidateKey    int64
 6   Year            int32
 7   Month           int32
 8   Day             int32
dtypes: int32(3), int64(4), object(2)
memory usage: 163.2+ MB

### Make numerical

In [12]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2852280 entries, 0 to 2852279
Data columns (total 9 columns):
 #   Column          Dtype
---  ------          -----
 0   QuestionKey     int64
 1   LeftStatement   object
 2   RightStatement  object
 3   AnswerVal       int64
 4   TestKey         int64
 5   CandidateKey    int64
 6   Year            int32
 7   Month           int32
 8   Day             int32
dtypes: int32(3), int64(4), object(2)
memory usage: 163.2+ MB

,QuestionKey,LeftStatement,RightStatement,AnswerVal,TestKey,CandidateKey,Year,Month,Day
0,1,BEW_1,BEH_1,1,166962,38114181,2019,1,2
1,2,REA_1,OPT_1,5,166962,38114181,2019,1,2
2,3,REG_1,AFW_1,5,166962,38114181,2019,1,2
3,4,RUS_1,ENE_1,5,166962,38114181,2019,1,2
4,5,OVE_1,GED_1,5,166962,38114181,2019,1,2

In [13]:
only_int = df.AnswerVal.apply(lambda x: x % 1 == 0).all()
if only_int:
    print('In the column AnswerVal none of the values have a value that needs to be stored as a float, therefor we can change the datatype to integer.')
    df['AnswerVal'] = df['AnswerVal'].astype(int)
df.info()

In the column AnswerVal none of the values have a value that needs to be stored as a float, therefor we can change the datatype to integer.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2852280 entries, 0 to 2852279
Data columns (total 9 columns):
 #   Column          Dtype
---  ------          -----
 0   QuestionKey     int64
 1   LeftStatement   object
 2   RightStatement  object
 3   AnswerVal       int32
 4   TestKey         int64
 5   CandidateKey    int64
 6   Year            int32
 7   Month           int32
 8   Day             int32
dtypes: int32(4), int64(3), object(2)
memory usage: 152.3+ MB

### Foutieve waarden

In [14]:
is_valid = df['AnswerVal'].isin([1, 2, 3, 4, 5]).all()

if not is_valid: 
    print("Some values in the AnswerVal column do not fall in the permitted range.")
    df = df[df['AnswerVal'].isin([1, 2, 3, 4, 5])]
else: 
    print("All values in the AnswerVal column fall in the permitted range.")

Some values in the AnswerVal column do not fall in the permitted range.

### Export to csv

In [15]:
df.set_index('TestKey', inplace=True)
df.to_csv('../csv/preprocessed_data.csv')
df.reset_index(inplace=True)

In [16]:
# df.reset_index(inplace=True)

## Ander idee

In [17]:
# wat ik wil maken 
# df_persoonlijkheid -> 'TestKey', 'Candidate', 'Year', 'Month', 'Day', 'BEH_score', 'REA_score', 'REG_score', ... , 'OPT_score'

In [18]:
df.head()

,TestKey,QuestionKey,LeftStatement,RightStatement,AnswerVal,CandidateKey,Year,Month,Day
0,166962,1,BEW_1,BEH_1,1,38114181,2019,1,2
1,166962,2,REA_1,OPT_1,5,38114181,2019,1,2
2,166962,3,REG_1,AFW_1,5,38114181,2019,1,2
3,166962,4,RUS_1,ENE_1,5,38114181,2019,1,2
4,166962,5,OVE_1,GED_1,5,38114181,2019,1,2

In [19]:
len(df.LeftStatement.unique())

134

In [20]:
df['LeftStatement_type'] = df['LeftStatement'].str.split('_').str[0]
df.head()

,TestKey,QuestionKey,LeftStatement,RightStatement,AnswerVal,CandidateKey,Year,Month,Day,LeftStatement_type
0,166962,1,BEW_1,BEH_1,1,38114181,2019,1,2,BEW
1,166962,2,REA_1,OPT_1,5,38114181,2019,1,2,REA
2,166962,3,REG_1,AFW_1,5,38114181,2019,1,2,REG
3,166962,4,RUS_1,ENE_1,5,38114181,2019,1,2,RUS
4,166962,5,OVE_1,GED_1,5,38114181,2019,1,2,OVE

In [21]:
len(df.LeftStatement_type.unique())

34

In [22]:
start = len(df.RightStatement.unique())
df['RightStatement_type'] = df['RightStatement'].str.split('_').str[0]
end = len(df.RightStatement_type.unique())

print('original length:', start)
print('remaining length:', end)
df.head()

original length: 136
remaining length: 35

,TestKey,QuestionKey,LeftStatement,RightStatement,AnswerVal,CandidateKey,Year,Month,Day,LeftStatement_type,RightStatement_type
0,166962,1,BEW_1,BEH_1,1,38114181,2019,1,2,BEW,BEH
1,166962,2,REA_1,OPT_1,5,38114181,2019,1,2,REA,OPT
2,166962,3,REG_1,AFW_1,5,38114181,2019,1,2,REG,AFW
3,166962,4,RUS_1,ENE_1,5,38114181,2019,1,2,RUS,ENE
4,166962,5,OVE_1,GED_1,5,38114181,2019,1,2,OVE,GED

In [23]:
df.drop(columns=['RightStatement', 'LeftStatement'], inplace=True)
df.head()

,TestKey,QuestionKey,AnswerVal,CandidateKey,Year,Month,Day,LeftStatement_type,RightStatement_type
0,166962,1,1,38114181,2019,1,2,BEW,BEH
1,166962,2,5,38114181,2019,1,2,REA,OPT
2,166962,3,5,38114181,2019,1,2,REG,AFW
3,166962,4,5,38114181,2019,1,2,RUS,ENE
4,166962,5,5,38114181,2019,1,2,OVE,GED

In [24]:
df['score_left'] = 6 - df.AnswerVal
df['score_right'] = df.AnswerVal
df.drop(columns=['AnswerVal'], inplace=True)
df.head()

,TestKey,QuestionKey,CandidateKey,Year,Month,Day,LeftStatement_type,RightStatement_type,score_left,score_right
0,166962,1,38114181,2019,1,2,BEW,BEH,5,1
1,166962,2,38114181,2019,1,2,REA,OPT,1,5
2,166962,3,38114181,2019,1,2,REG,AFW,1,5
3,166962,4,38114181,2019,1,2,RUS,ENE,1,5
4,166962,5,38114181,2019,1,2,OVE,GED,1,5

In [25]:
left = df.groupby(['TestKey', 'LeftStatement_type'])['score_left'].sum().unstack(fill_value=0)
left.reset_index(inplace=True)
left.head()

LeftStatement_type,TestKey,AHA,AHZ,APZ,AZA,BEW,BHA,BHZ,BPZ,BXZ,...,OVE,PLI,REA,REG,RUS,SAL,STA,VOL,ZEL,ZIC
0,166962,0,0,0,0,14,0,0,0,0,...,14,10,10,18,18,11,18,20,22,19
1,166963,0,0,0,0,19,0,0,0,0,...,14,13,19,21,24,14,20,19,22,18
2,166964,0,0,0,0,20,0,0,0,0,...,15,18,13,15,20,20,15,19,18,14
3,166965,0,0,0,0,13,0,0,0,0,...,13,10,8,11,10,11,10,12,11,12
4,166966,0,0,0,0,23,0,0,0,0,...,18,18,20,20,18,16,20,18,19,19

In [26]:
right = df.groupby(['TestKey', 'RightStatement_type'])['score_right'].sum().unstack(fill_value=0)
right.reset_index(inplace=True)
right.head()

RightStatement_type,TestKey,AFW,AHA,AHZ,AMB,AND,APZ,AXZ,BEH,BHA,...,EXZ,EZA,GED,INB,LEI,OPT,PLA,SAM,SBE,ZFS
0,166962,18,0,0,18,17,0,0,22,0,...,0,0,22,11,16,26,20,14,25,26
1,166963,15,0,0,16,18,0,0,17,0,...,0,0,22,14,17,17,21,14,22,23
2,166964,21,0,0,21,22,0,0,16,0,...,0,0,21,16,17,23,19,18,16,18
3,166965,25,0,0,26,24,0,0,23,0,...,0,0,23,30,24,28,23,25,25,26
4,166966,16,0,0,16,17,0,0,13,0,...,0,0,18,21,18,16,16,17,20,18

In [27]:
print('right columns:', right.columns)
print('left columns:', left.columns)

right columns: Index(['TestKey', 'AFW', 'AHA', 'AHZ', 'AMB', 'AND', 'APZ', 'AXZ', 'BEH',
       'BHA', 'BPZ', 'BZA', 'CHA', 'CPZ', 'CXZ', 'CZA', 'DHA', 'DOE', 'DPZ',
       'DXZ', 'DZA', 'EHA', 'EHZ', 'ENE', 'EPZ', 'EXT', 'EXZ', 'EZA', 'GED',
       'INB', 'LEI', 'OPT', 'PLA', 'SAM', 'SBE', 'ZFS'],
      dtype='object', name='RightStatement_type')
left columns: Index(['TestKey', 'AHA', 'AHZ', 'APZ', 'AZA', 'BEW', 'BHA', 'BHZ', 'BPZ',
       'BXZ', 'CHA', 'CPZ', 'CXZ', 'CZA', 'DEN', 'DHA', 'DHZ', 'DOB', 'DXZ',
       'DZA', 'EHA', 'EXZ', 'EZA', 'FLE', 'INT', 'OVE', 'PLI', 'REA', 'REG',
       'RUS', 'SAL', 'STA', 'VOL', 'ZEL', 'ZIC'],
      dtype='object', name='LeftStatement_type')

In [28]:
res = left.merge(right, on='TestKey')
print('all columns:', res.columns)
res.head()

all columns: Index(['TestKey', 'AHA_x', 'AHZ_x', 'APZ_x', 'AZA', 'BEW', 'BHA_x', 'BHZ',
       'BPZ_x', 'BXZ', 'CHA_x', 'CPZ_x', 'CXZ_x', 'CZA_x', 'DEN', 'DHA_x',
       'DHZ', 'DOB', 'DXZ_x', 'DZA_x', 'EHA_x', 'EXZ_x', 'EZA_x', 'FLE', 'INT',
       'OVE', 'PLI', 'REA', 'REG', 'RUS', 'SAL', 'STA', 'VOL', 'ZEL', 'ZIC',
       'AFW', 'AHA_y', 'AHZ_y', 'AMB', 'AND', 'APZ_y', 'AXZ', 'BEH', 'BHA_y',
       'BPZ_y', 'BZA', 'CHA_y', 'CPZ_y', 'CXZ_y', 'CZA_y', 'DHA_y', 'DOE',
       'DPZ', 'DXZ_y', 'DZA_y', 'EHA_y', 'EHZ', 'ENE', 'EPZ', 'EXT', 'EXZ_y',
       'EZA_y', 'GED', 'INB', 'LEI', 'OPT', 'PLA', 'SAM', 'SBE', 'ZFS'],
      dtype='object')

,TestKey,AHA_x,AHZ_x,APZ_x,AZA,BEW,BHA_x,BHZ,BPZ_x,BXZ,...,EXZ_y,EZA_y,GED,INB,LEI,OPT,PLA,SAM,SBE,ZFS
0,166962,0,0,0,0,14,0,0,0,0,...,0,0,22,11,16,26,20,14,25,26
1,166963,0,0,0,0,19,0,0,0,0,...,0,0,22,14,17,17,21,14,22,23
2,166964,0,0,0,0,20,0,0,0,0,...,0,0,21,16,17,23,19,18,16,18
3,166965,0,0,0,0,13,0,0,0,0,...,0,0,23,30,24,28,23,25,25,26
4,166966,0,0,0,0,23,0,0,0,0,...,0,0,18,21,18,16,16,17,20,18

In [29]:
res.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16680 entries, 0 to 16679
Data columns (total 70 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   TestKey  16680 non-null  int64
 1   AHA_x    16680 non-null  int32
 2   AHZ_x    16680 non-null  int32
 3   APZ_x    16680 non-null  int32
 4   AZA      16680 non-null  int32
 5   BEW      16680 non-null  int32
 6   BHA_x    16680 non-null  int32
 7   BHZ      16680 non-null  int32
 8   BPZ_x    16680 non-null  int32
 9   BXZ      16680 non-null  int32
 10  CHA_x    16680 non-null  int32
 11  CPZ_x    16680 non-null  int32
 12  CXZ_x    16680 non-null  int32
 13  CZA_x    16680 non-null  int32
 14  DEN      16680 non-null  int32
 15  DHA_x    16680 non-null  int32
 16  DHZ      16680 non-null  int32
 17  DOB      16680 non-null  int32
 18  DXZ_x    16680 non-null  int32
 19  DZA_x    16680 non-null  int32
 20  EHA_x    16680 non-null  int32
 21  EXZ_x    16680 non-null  int32
 22  EZA_x    16680 non-null  int32
 23  FLE      16680 non-null  int32
 24  INT      16680 non-null  int32
 25  OVE      16680 non-null  int32
 26  PLI      16680 non-null  int32
 27  REA      16680 non-null  int32
 28  REG      16680 non-null  int32
 29  RUS      16680 non-null  int32
 30  SAL      16680 non-null  int32
 31  STA      16680 non-null  int32
 32  VOL      16680 non-null  int32
 33  ZEL      16680 non-null  int32
 34  ZIC      16680 non-null  int32
 35  AFW      16680 non-null  int32
 36  AHA_y    16680 non-null  int32
 37  AHZ_y    16680 non-null  int32
 38  AMB      16680 non-null  int32
 39  AND      16680 non-null  int32
 40  APZ_y    16680 non-null  int32
 41  AXZ      16680 non-null  int32
 42  BEH      16680 non-null  int32
 43  BHA_y    16680 non-null  int32
 44  BPZ_y    16680 non-null  int32
 45  BZA      16680 non-null  int32
 46  CHA_y    16680 non-null  int32
 47  CPZ_y    16680 non-null  int32
 48  CXZ_y    16680 non-null  int32
 49  CZA_y    16680 non-null  int32
 50  DHA_y    16680 non-null  int32
 51  DOE      16680 non-null  int32
 52  DPZ      16680 non-null  int32
 53  DXZ_y    16680 non-null  int32
 54  DZA_y    16680 non-null  int32
 55  EHA_y    16680 non-null  int32
 56  EHZ      16680 non-null  int32
 57  ENE      16680 non-null  int32
 58  EPZ      16680 non-null  int32
 59  EXT      16680 non-null  int32
 60  EXZ_y    16680 non-null  int32
 61  EZA_y    16680 non-null  int32
 62  GED      16680 non-null  int32
 63  INB      16680 non-null  int32
 64  LEI      16680 non-null  int32
 65  OPT      16680 non-null  int32
 66  PLA      16680 non-null  int32
 67  SAM      16680 non-null  int32
 68  SBE      16680 non-null  int32
 69  ZFS      16680 non-null  int32
dtypes: int32(69), int64(1)
memory usage: 4.5 MB

In [30]:
res.to_csv('../csv/preprocessing_pyod.csv', index=False)